### ISSUE TITLE
Java 9 compilation issue

### ISSUE THREAD

**Issue by vmironichev** [sherter/google-java-format-gradle-plugin#23]
Hi! I am seeing following error when trying to build project with Java 9 and Gradle 4.2.1. Please let me know if you think that is an issue of Gradle. Thanks.

Gradle 4.2.1
Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9 (Oracle Corporation 9+181)
OS:           Mac OS X 10.13 x86_64

`failed to process file
java.lang.NoClassDefFoundError: javax/lang/model/element/Modifier
        at com.google.googlejavaformat.java.ModifierOrderer.getModifier(ModifierOrderer.java:45)
        at com.google.googlejavaformat.java.ModifierOrderer.asModifier(ModifierOrderer.java:153)
        at com.google.googlejavaformat.java.ModifierOrderer.reorderModifiers(ModifierOrderer.java:100)
        at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:180)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:163)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:149)
        at com.google.googlejavaformat.java.Formatter$formatSource.call(Unknown Source)
        at com.github.sherter.googlejavaformatgradleplugin.format.OneDotOneFactory$_create_closure1.doCall(OneDotOneFactory.groovy:31)
        at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
        at com.sun.proxy.$Proxy70.format(Unknown Source)
        at com.github.sherter.googlejavaformatgradleplugin.FormatFileCallable.call(FormatFileCallable.java:39)
        at com.github.sherter.googlejavaformatgradleplugin.FormatFileCallable.call(FormatFileCallable.java:13)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
`

**Comment by sherter** [comment]
This error occurs while running the tests and not during the actual "build" (`gradle assemble`), right?

This has probably something to do with the module system in Java 9, which I haven't been able to look into very much. The error says that google-java-format can't access a class that should be part of the JRE, so there is probably a module dependency declaration missing somewhere.

I'll look into it when I find some free time (which is rare right now, so please don't be disappointed if this takes a while ..). Contributions are welcome :wink:

**Comment by sherter** [comment]
Compiling with javac 9 (and running on jre 9 with gradle versions > 4.2.1) should work now (1f491f3eef144bdba66643593e5c92b39894196c).  Feel free to re-open if you still have issues.

**Comment by sudhirj** [comment]
Can you make a release? Or can we just hit master.

**Comment by dviktorov** [comment]
Same issue happens on JDK10. Was there any release to fix it?

**Comment by sherter** [comment]
Not yet, sorry. Maybe this weekend.

**Comment by sherter** [comment]
@dviktorov @sudhirj sorry for the delay, new release (v0.7.1) landed in the plugin portal.
